자료구조, 알고리즘 항목의 목차를 업데이트 하였습니다.
zrma/cs pull request #3
Opened 2021-04-04 15:07 UTC by namonak

2021-04-06 16:26 UTC, zrma requested changes
수정 요청이 일부 있습니다.

2021-04-06 16:26 UTC, zrma commented on linear_ds.MD
> +<img src="./images/stack.png" width="350px" height="" alt="stack"></img><br/>
그림에 대한 저작권 위반이 우려됩니다.

2021-04-06 16:26 UTC, zrma commented on linear_ds.MD
> +<img src="./images/queue.png" width="450px" height="" alt="queue"></img><br/>
마찬가지로 그림에 대한 저작권 위반이 우려됩니다.

2021-04-06 16:26 UTC, zrma commented on linear_ds.MD
> +* Pop() : 큐의 앞(front)에 원소를 삭제
삭제가 아니라 인출이 아닐까요?

2021-04-06 16:26 UTC, zrma commented on linear_ds.MD
> +* Rear() : 큐의 뒤(rear)에 있는 원소를 반환
선입 선출 자료구조에서 rear 데이터를 반환할 필요가 있을까요?\
rear 데이터가 필요하다면 [double ended queue](https://en.wikipedia.org/wiki/Double-ended_queue)를 고려하는게 좋을 것 같습니다.

2021-04-06 16:26 UTC, zrma commented on linear_ds.MD
> +* Front() : 큐의 앞(front)에 있는 원소를 반환
`Front` 보다는 `Pick`이 어떨까요?

2021-04-06 16:26 UTC, zrma commented on linear_ds.MD
> +큐는 선입선출([**FIFO**](https://ko.wikipedia.org/wiki/선입_선출), First In First Out) 특성을 갖는 자료구조이며, 대기열이라고도 칭한다. 큐는 한쪽 끝에서 삽입이 일어나고 그 반대쪽 끝에서 삭제가 일어나는 순서 리스트이다. 새로운 데이터가 삽입되는 끝을 리어(rear)라고 하고 데이터가 삭제되는 끝을 프런
순서 리스트라는 표현이 이상해요.

그리고 굳이 영문 단어를 어색한 한국어식 표현으로 `리어`, `프런트`라고 표기하지 않았으면 좋겠어요.

2021-04-06 16:26 UTC, zrma commented on linear_ds.MD
> +스택은 후입선출([**LIFO**](https://ko.wikipedia.org/wiki/후입_선출), Last In First Out) 특성을 갖는 자료구조이다. 스택은 톱(top)이라고 하는 한쪽 끝에서 데이터의 모든 삽입(push)과 삭제(pop)가 일어나는 순서 리스트이다. 즉 마지막에 들어간 항목이 가장 먼저 나오는 자료구조이다.
여기도 영문 단어를 굳이 `톱`으로 표기하지 않았으면 좋겠어요.

2021-04-11 12:45 UTC, closed without merging

2021-04-11 12:46 UTC, namonak commented on linear_ds.MD
> +<img src="./images/stack.png" width="350px" height="" alt="stack"></img><br/>
해당 커밋을 통해 [6925677](https://github.com/namonak/cs/commit/692567748c4ba5c756d7d32eca40e98c2a625680) 그림을 수정하였습니다.

2021-04-11 12:47 UTC, namonak commented on linear_ds.MD
> +<img src="./images/queue.png" width="450px" height="" alt="queue"></img><br/>
해당 커밋을 통해 [6925677](https://github.com/namonak/cs/commit/692567748c4ba5c756d7d32eca40e98c2a625680) 그림을 수정하였습니다.

2021-04-11 12:51 UTC, zrma commented on linear_ds.MD
> +<img src="./images/stack.png" width="350px" height="" alt="stack"></img><br/>
과거의 커밋 히스토리에 이미 해당 그림이 업로드 되어 저작권을 위반하였으므로\
적절하게 git rebase 과정 중 해당 이미지를 [처음 업로드 한 커밋과, 수정 커밋을 squash를 통해 합쳐서](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\
처음부터 해당 이미지가 업로드 되지 않은 것처럼 만드는 게 좋을 것 같아요.

2021-04-11 12:52 UTC, zrma commented on linear_ds.MD
> +<img src="./images/queue.png" width="450px" height="" alt="queue"></img><br/>
> 해당 커밋을 통해 [6925677](https://github.com/namonak/cs/commit/692567748c4ba5c756d7d32eca40e98c2a625680) 그림을 수정하였습니다.

https://github.com/zrma/cs/pull/3#discussion_r611184268 참고 부탁드려요.